apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastalert
  labels:
    name: elastalert
spec:
  capacity:
    storage: 1G
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: vol-08901d058d0c91ebb
    fsType: ext4