kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: elastalert-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1G
  selector:
    matchLabels:
      name: elastalert