apiVersion: v1
kind: ReplicationController
metadata:
  name: elastalert
  labels:
    tier: backend
    role: support
    name: elastalert
spec:
  replicas: 1
  selector:
    name: elastalert
  template:
    metadata:
      labels:
        name: elastalert
    spec:
      volumes:
        - name: elastalert-volume
          persistentVolumeClaim:
            claimName: elastalert-volume
      containers:
        - name: elastalert-storage
          image: elasticsearch:2-alpine
          ports:
            - containerPort: 9200
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elastalert-volume
        - name: elastalert
          image: 944590742144.dkr.ecr.eu-west-1.amazonaws.com/apply/smart-elastalert:latest
          resources:
            limits:
              cpu: 100m
              memory: 200Mi
          env:
            - name: ELASTICSEARCH_HOST
              value: "localhost"
            - name: ELASTICSEARCH_PORT
              value: "9200"
      imagePullSecrets:
        - name: registry-key
      nodeSelector:
        beta.kubernetes.io/instance-type: t2.medium